#!/bin/bash

$CMAKE_BIN \
    -DCOMPILER_DIR=$COMPILER_DIR \
    -DBUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE \
    -B $GTEST_BUILD_DIR \
    -S $GTEST_REPOSITORY_DIR
$CMAKE_BIN \
    --build \
    $GTEST_BUILD_DIR
$CMAKE_BIN \
    -DCMAKE_INSTALL_PREFIX=$GTEST_INSTALL_DIR \
    -P $GTEST_BUILD_DIR/cmake_install.cmake

$CMAKE_BIN \
    -DCOMPILER_DIR=$COMPILER_DIR \
    -DBUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE \
    -DRANGE_V3_HEADER_CHECKS=0 \
    -DRANGE_V3_DOCS=0 \
    -DRANGE_V3_TESTS=0 \
    -DRANGE_V3_EXAMPLES=0 \
    -DRANGE_V3_PERF=0 \
    -B $RANGEV3_BUILD_DIR \
    -S $RANGEV3_REPOSITORY_DIR
$CMAKE_BIN \
    --build \
    $RANGEV3_BUILD_DIR
$CMAKE_BIN \
    -DCMAKE_INSTALL_PREFIX=$RANGEV3_INSTALL_DIR \
    -P $RANGEV3_BUILD_DIR/cmake_install.cmake
