#!/bin/bash

$CMAKE_BIN \
    -DCOMPILER_DIR=$COMPILER_DIR \
    -DBUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE \
    -DGTEST_LIBRARY=$GTEST_LIBRARY \
    -DGTEST_MAIN_LIBRARY=$GTEST_MAIN_LIBRARY \
    -DGTEST_INCLUDE_DIR=$GTEST_INCLUDE_DIR \
    -DNJSON_INCLUDE_DIR=$NJSON_INCLUDE_DIR \
    -DMAGIC_GET_INSTALL_DIR=$MAGIC_GET_INSTALL_DIR \
    -DRange-v3_DIR=$RANGEV3_INSTALL_DIR/lib/cmake/range-v3 \
    -DRANGEV3_INCLUDE_DIR=$RANGEV3_INCLUDE_DIR \
    -B $ROOT_BUILD_DIR \
    -S $ROOT_REPOSITORY_DIR
$CMAKE_BIN \
    --build \
    $ROOT_BUILD_DIR
$CMAKE_BIN \
    -DCMAKE_INSTALL_PREFIX=$ROOT_INSTALL_DIR \
    -P $ROOT_BUILD_DIR/cmake_install.cmake
