#!/bin/bash

export PROTOBUF_REPOSITORY_DIR=$ROOT_REPOSITORY_DIR/submodules/protobuf
export PROTOBUF_CMAKE_DIR=$PROTOBUF_REPOSITORY_DIR/cmake
export PROTOBUF_BUILD_DIR=$PROTOBUF_REPOSITORY_DIR/cmake/build
export PROTOBUF_INSTALL_DIR=$PROTOBUF_REPOSITORY_DIR/cmake/build/install
