name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install snap
      run: sudo bash scripts/install_snap.sh

    - name: Init submodule
      run: git submodule update --init --recursive

    - name: Prepare compiler
      run: bash prepare_compiler.sh

    - name: Bootstrap
      run: CMAKE_BIN="snap run cmake" bash bootstrap.sh

    - name: Build
      run: CMAKE_BIN="snap run cmake" bash build.sh

   - name: Test
     run: build/src/05_without_gmock/05_without_gmock
